# Generated by Django 4.2.4 on 2023-08-18 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('productName', models.TextField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
